pipeline
{
	agent any
	stages 
	{
		stage('Builder') 
		{
			steps 
			{
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dtr_dcdevjbz',
						usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) 
				{
					script
					{
						powershell 'docker build -f ${PWD}\\buildertools\\basicbuilder\\Dockerfile -t dcdevjbz/msbuilder15.4.8.50001_base:wincore1709 ${PWD}\\buildertools\\basicbuilder'
						powershell '${env:PASSWORD} | docker login --username ${env:USERNAME} --password-stdin ; docker push dcdevjbz/msbuilder15.4.8.50001_base:wincore1709'
					}
				}
			}
		}
	}
}