pipeline
{
	agent any
	environment
	{
		MY_DTRID=''
		MY_DTRPASSWORD=''	
	}
	stages 
	{
		stage('Builder') 
		{
			steps 
			{
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'mydtr_cre',
						usernameVariable: ${MY_DTRID}, passwordVariable: ${MY_DTRPASSWORD}]]) 
				{					
				}

				script
				{
					//powershell 'docker build -f ${PWD}\\buildertools\\basicbuilder\\Dockerfile -t dcdevjbz/msbuilder15.4.8.50001_base:wincore1709 ${PWD}\\buildertools\\basicbuilder'
					powershell '${env:MY_DTRPASSWORD} | docker login --username ${env:MYDTRID} --password-stdin'
				}
			}
		}
	}
}